name: Node.js CI & Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Reduced matrix to save resources, can add 22.x back if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Cache npm dependencies

    - name: Install dependencies
      run: npm ci # Use npm ci for cleaner installs in CI

    - name: Run linters
      run: npm run lint # Assumes 'lint' script is in package.json

    - name: Run tests
      run: npm test # Assumes 'test' script is in package.json
